Change `uusd` to `base_denom`
nebula-protocol/nebula-contracts pull request #171
Opened 2022-06-02 08:17 UTC by Benzbeeb

2022-06-02 09:01 UTC, traviolus requested changes

2022-06-02 09:01 UTC, traviolus commented on contracts/nebula-collector/README.md
>  - Cluster tokens accrued through protocol fees to UST
replace UST with BASE_DENOM

2022-06-02 09:01 UTC, traviolus commented on contracts/nebula-incentives/README.md
> +- `min_ust`: minimum amount of BASE_DENOM expected to receive back when selling the minted cluster tokens on Astroport (for slippage control)
if we gonna replace all UST in the code to BASE_DENOM maybe we should rename this variable too?

2022-06-02 09:01 UTC, traviolus commented on packages/nebula_protocol/src/collector.rs
> +    /// Convert swaps BASE_DENOM to NEB or any CT token to UST.
UST?

2022-06-16 06:11 UTC, songwongtp approved these changes

2022-06-16 06:11 UTC, merged